#!/bin/bash

enable_emu(){
	clear
	trunkurl="$emuurl"
	touch "$workdir/EMU_ON"
	check_url "$trunkurl" && checkout 2>/dev/null
}

disable_emu(){
	clear
	source "$configdir/urls"
	[ -f "$workdir/oscamsource.url" ] && source "$workdir/oscamsource.url"
	[ -f "$workdir/EMU_ON" ] && rm -f "$workdir/EMU_ON"
	check_url "$trunkurl" && checkout 2>/dev/null
}
