#!/bin/bash

update_me(){
	clear;s3logo;
	local_revision=0;
	online_revision=0;
	source "$configdir/urls";
	s3local="$dldir/s3_github";
	echo -en "  s3_git CHECK:\n  -------------\n";
	if [ -d "$workdir/.git" -a ! -d "$workdir/.svn" ]; then
		pushd $workdir >/dev/null
		local_revision=$(git rev-list --count HEAD 2>/dev/null);
		popd >/dev/null
	elif [ -d "$s3local/.svn" ]; then
		local_revision=$(gitrevision $s3local);
	fi
	online_revision=$(gitrevision $s3url)
	if [ ! $local_revision == $online_revision ]; then
		printf "  update s3_git to\n  Local Revision: $online_revision\n"
		if [ -d "$workdir/.git" -a ! -d "$workdir/.svn" ]; then
			pushd $workdir >/dev/null
			git pull -q
			popd >/dev/null
		else
			svn -q checkout "$s3url" "$s3local";
			cd "$s3local";
			echo -en "  update all files ...\n\n";
			yes | cp -rf ./s3 "$workdir/s3";
			yes | cp -rf ./support/* "$workdir/support";
	else
		printf "  is up to date\n  Online Revision: $online_revision\n\n"
	fi
	sleep 1
}

update_emu(){
	clear;s3logo;
	local_revision=0;
	online_revision=0;
	source "$configdir/urls";
	emulocal="$dldir/emu_github";
	echo -en "  emu_git CHECK:\n  --------------\n";
	if [ -d "$emulocal/.git" -a ! -d "$emulocal/.svn" ]; then
		pushd $emulocal >/dev/null
		local_revision=$(git rev-list --count HEAD 2>/dev/null);
		popd >/dev/null
	elif [ -d "$emulocal" ]; then
		rm -rf "$emulocal"
	fi

	online_revision=$(gitrevision $emuurl)
	if [ ! "$local_revision" == "$online_revision" ]; then
		printf "  update emu_git to\n  Local Revision: $online_revision\n"
		git clone -q "$emuurl" "$emulocal";
	else
		printf "  is up to date\n  Online Revision: $online_revision\n"
	fi
	if [ -f "$emulocal/VERSION" ]
	then
		printf "  EmuVersion: "
		grep '\$Version:' "$emulocal/VERSION" |cut -d " " -f 2
		_nl
	fi
	sleep 1
}

fix_me(){
	clear
	s3logo
	source "$configdir/urls"
	s3local="$dldir/s3_github"
	emulocal="$dldir/emu_github"

	if [ -d "$s3local" ]
	then
		rm -rf $s3local
		update_me
	else
		update_me
	fi

	if [ -d "$emulocal" ]
	then
		rm -rf $emulocal
		update_emu
	else
		update_emu
	fi
}
