#!/bin/bash

update_me(){
	clear;s3logo;
	local_revision=0;
	online_revision=0;
	source "$configdir/urls";
	s3local="$dldir/s3_github";
	echo -en "  s3_git CHECK:\n  -------------\n";
	if [ -d "$s3local/.svn" ]; then
		local_revision=$(gitrevision $s3local);
	fi
	online_revision=$(gitrevision $s3url);
	if [ ! $local_revision == $online_revision ]; then
		echo -en "  update s3_git to\n  Local Revision: $online_revision\n";
		svn -q checkout "$s3url" "$s3local";
		cd "$s3local";
		echo -en "  update all files ...\n\n";
		yes | cp -rf ./s3 "$workdir/s3";
		yes | cp -rf ./support/functions/* "$workdir/support/functions/";
	else
		echo -en "  is up to date\n  Online Revision: $online_revision\n\n";
	fi
	sleep 1;
}

update_emu(){
	clear;s3logo;
	local_revision=0;
	online_revision=0;
	source "$configdir/urls";
	emulocal="$dldir/emu_github";
	echo -en "  emu_git CHECK:\n  --------------\n";
	if [ -d "$emulocal/.svn" ]; then
		local_revision=$(gitrevision $emulocal);
	fi
	online_revision=$(gitrevision $emuurl);
	if [ ! $local_revision == $online_revision ]; then
		echo -en "  update emu_git to\n  Local Revision: $online_revision\n\n";
		svn -q checkout "$emuurl" "$emulocal";
	else
		echo -en "  is up to date\n  Online Revision: $online_revision\n\n";
	fi
	sleep 1;
}

fix_me(){
	clear;s3logo;
	source "$configdir/urls";
	s3local="$dldir/s3_github";
	if [ -d "$s3local/.svn" ];then
		cd "$s3local";
		echo -en "  overwrite all files ...\n\n";
		yes | cp -rf ./s3 "$workdir/s3";
		yes | cp -rf ./support/functions/* "$workdir/support/functions/";
	else
		update_me;
		fix_me;
	fi
}

update_all(){
update_me;
update_emu;
}
