#!/bin/bash

update_me(){
	clear;s3logo
	local_revision=0
	online_revision=0
	source "$configdir/urls"
	s3local="$dldir/s3_github"
	printf "  s3_git CHECK:\n  -------------\n"
	check_url "$s3url" || return

	local_revision=$(gitrevision $s3local)
	online_revision=$(gitrevision $s3url)

	if [ ! "$local_revision" == "$online_revision" ]
	then
		printf "  update s3_git\n   from Local Revision: $local_revision\n   to  Remote Revision: $online_revision\n"
		rm -rf "$s3local"; git clone "$s3url" "$s3local" &>/dev/null; cd "$s3local"
		printf "  updating all files ...\n\n"
		yes | cp -rf ./s3 "$workdir/s3"
		yes | cp -rf ./support/* "$workdir/support"
	else
		printf "  is up to date\n   Online Revision: $online_revision\n\n"
	fi
	sleep 1
}

update_emu(){
	clear;s3logo
	local_revision=0
	online_revision=0
	source "$configdir/urls"
	emulocal="$dldir/emu_github"
	printf "  emu_git CHECK:\n  --------------\n"
	check_url "$emuurl" || return

	local_revision=$(gitrevision $emulocal)
	online_revision=$(gitrevision $emuurl)

	if [ ! "$local_revision" == "$online_revision" ]
	then
		printf "  update emu_git\n   from Local Revision: $local_revision\n   to  Remote Revision: $online_revision\n"
		rm -rf "$emulocal"; git clone "$emuurl" "$emulocal" &>/dev/null
	else
		printf "  is up to date\n   Online Revision: $online_revision\n"
	fi

	printf "   Emu-Version: "
	grep '#define EMU_VERSION' $emulocal/* | head -1 | awk '{print $3}'; _nl
	sleep 1
}

fix_me(){
	clear
	s3logo
	source "$configdir/urls"
	s3local="$dldir/s3_github"
	emulocal="$dldir/emu_github"

	[ -d "$s3local" ] && rm -rf $s3local
	update_me
	[ -d "$emulocal" ] && rm -rf $emulocal
	update_emu
}
