readers_on
USE_LIBUSB USE_COMPRESS USE_SSL USE_LIBCRYPTO USE_PCSC USE_UTF8
WEBIF LIVELOG JQUERY TOUCH SSL DVBAPI NEUTRINO READ_SDT IRDETO_GUESSING ANTICASC DEBUG MONITOR LB CACHEEX CWCC LCD LED IPV6 EMU CARDLIST
CAMD35 CAMD35_TCP NEWCAMD CCCAM CCCSHARE GBOX SCAM
PHOENIX INTERNAL SC8IN1 MP35 SMARGO DB2COM STAPI STAPI5 STINGER DRECAS
