#!/bin/bash

#simplebuild_plugin vlmcsd

build_vlmcsd() {
clear
source "$tccfgdir/$1"
filename="svn1113.tar.gz"
sourcedir="vlmcsd-svn1113"
stable="https://github.com/Wind4/vlmcsd/archive/$filename"

cd $dldir
slogo
[ -d $sourcedir ] && rm -rf $sourcedir #remove build dir
[ -f $filename ] && rm -f $filename #remove download
echo -en "\nVLMCSD\n=======\ndownload please wait ... "
wget $stable --progress=dot -q --show-progress 2>&1 |
awk 'NF>2 && $(NF-2) ~ /%/{printf "\rdownload please wait ... %s",$(NF-2)} END{print "\rdownload please wait ... Done!"}' #download stable package
echo -e "extracting please wait ... "

tar -zxf $filename #extract source
cd $sourcedir

#build software
make CC=/opt/s3_releases/support/toolchains/dream_one/bin/aarch64-dream_one-linux-gnu-gcc 2>&1 |grep --line-buffered -v "^make" |awk -F "CC" '{print "compile -> " "\033[32m" $NF "\033[0m" }'
[ -d bin ] && cd bin
upx -9 -q vlmcs |grep vlmcs |awk '{print "compress -> " $1" "$3" "$4 }'
upx -9 -q vlmcsd |grep vlmcsd |awk '{print "compress -> " $1" "$3" "$4 }'

#copy binarys
[ -d "$sodir/$sourcedir-$_toolchainname" ] && rm -rf "$sodir/$sourcedir-$_toolchainname"
mkdir -p "$sodir/$sourcedir-$_toolchainname"
mv {vlmcs,vlmcsd} "$sodir/$sourcedir-$_toolchainname"

}

if [ "$1" = "vlmcsd" ]; then
  build_vlmcsd $2
  exit
fi
