#!/bin/bash

#bulgarian

txt_as='като';
txt_of='от';
txt_for='за';
txt_b2="билд";
txt_to="към";
txt_now='сега';
txt_b1='билд';
txt_menu='меню';
txt_done=' готово';
txt_no='не';
txt_use='използва';
txt_back='назад';
txt_error='грешка';
txt_loading='зареждам'; #8 chars
txt_sel='избор';
txt_delete='изтрий';
txt_found='открити';
txt_create='създай';
txt_conf='конфигурация';
txt_extracting='извличане '; #10 chars
txt_wait='изчакайте...';
txt_existing='съществува';
txt_profiles='профили';
txt_not_found='не е намерено';
txt_n_installed='не е инсталирано';
txt_back_main="обратно към основно меню";
txt_too_old='(твърде стар или не се поддържа)';
txt_selected='избран';
txt_update='опреснявам';
txt_tc="Toolchain      ";
txt_tpl="Шаблон"
txt_lib="Библиотека"

# menu txt
txt_start_menu='Главно меню';
txt_remove_menu='Премахни toolchain';
txt_add_menu='Добави toolchain';
txt_main_revision="\n локална $(REPO) ревизия е : r";

# help txt
txt_help1="започнете с"
txt_help2="Параметрите на командния ред са"
txt_help3="[ENTER] за продължаване..."

# firstmenu ################################################
txt_firstmenu_continue="продължи с локалния $(REPO)";
   txt_firstmenu_chose="зареди различен $(REPO) (7000+)";
   txt_firstmenu_cedit="стартирай конфигурационния редактор";
   txt_firstmenu_tcupdate="стартирай опресняване на toolchain"; 
    txt_firstmenu_lang="ръчен избор на системен език";
    txt_firstmenu_exit="затвори simplebuild сега";

# _toolchain_config_menu ###################################
     txt_config_menu="конфигурационно меню";
      txt_back_build="назад към билд меню";
txt_module_configure="избери oscam модулите ";
     txt_oscam_extra="избери oscam екстрите USB/PCSC";
     txt_build_extra="избери билд екстрите компресиране/пач";
      txt_build_load="зареди последната конфигурация";
      txt_build_save="запази конфигурацията";
     txt_build_reset="ресет на конфигурацията";

# _toolchain_build_menu#####################################
 txt_bmenu_title="билд меню";
  txt_bmenu_user="потребител ";
  txt_bmenu_comp="компилатор       ";
  txt_bmenu_debu="debug инфо       ";
   txt_bmenu_use="USE_променливи ";
 txt_bmenu_build="компилирай oscam сега";
txt_bmenu_config="oscam/билд конфигурация";
txt_bmenu_update="инсталирай/опресни библиотеките";
txt_bmenu_backup="бекъп на toolchain";
  txt_bmenu_log="покажи последния билд.лог";
  txt_bmenu_back="обратно към избор на toolchain";
   txt_compress1="размер на файла преди     ";
   txt_compress2="размер на файла след      ";
   txt_compress3="файловия размер е редуциран до ";

#  _toolchain_main_menu#####################################
txt_menu_builder1="затвори simplebuild";
txt_menu_builder2="добави нов toolchain";
txt_menu_builder3="премахни инсталиран toolchain";
txt_menu_builder4="локален билд за";
txt_menu_builder5="създай нов toolchain";
txt_menu_back="обратно към меню toolchain";

# _dialog_checkout
txt_verify_syscheck='проверявам системата:';
     txt_verify_svn='проверявам съществуващия '$(REPO)':';
     txt_update_svn="$txt_update $(REPO):";
    txt_prepare_svn="подготвям $(REPO) checkout:";
         txt_latest="последен $(REPO)";

# _load_profile ###########################################
  txt_select_profile_title="налични профили";
        txt_select_profile="моля изберете профил";
txt_confirm_profile_select="моля потвърдете избора на:";
      txt_no_profile_found="няма открит профил в\n\n$profdir";

# _upload_cam #############################################
txt_upload_cam1="ssh профила не съществува";
txt_upload_cam2="ssh профил е открит";

# _plugin_update_toolchain #############################################
txt_s3tup_menu_command_label_exit="Exit"
txt_s3tup_menu_command_label_back="Back"
txt_s3tup_menu_command_label_create="Create"
txt_s3tup_menu_command_label_update="Update"
txt_s3tup_menu_command_label_backup="Backup"
txt_s3tup_menu_command_label_start="Start"
txt_s3tup_menu_command_label_info="Info"
txt_s3tup_menu_command_label_setup="Setup"
txt_s3tup_menu_command_label_edit="Edit"
txt_s3tup_menu_command_label_yes="Yes"
txt_s3tup_menu_command_label_no="No"

txt_s3tup_msg_syscheck1="Please wait while performing checks of required tools and dependencies..."
txt_s3tup_msg_syscheck2="You need to manually install the following packages to use this plugin properly:"
txt_s3tup_msg_reset_config1="Moving existing config file..."
txt_s3tup_msg_reset_config2="config file backup="
txt_s3tup_msg_reset_config3="Creating new config file. Please wait..."
txt_s3tup_msg_reset_config4="config file="
txt_s3tup_msg_reset_config5="You can change/extend them to fit your needs."
txt_s3tup_msg_buildasroot_error1="The cross ${txt_tc} build process was aborted because it must not run as root!"
txt_s3tup_msg_buildasroot_error2="If you are aware of the danger of building ${txt_tc}s as root and you know what you are doing,\n         you can force it with the following command:"
txt_s3tup_msg_toolchain_exists="${txt_tc} already exists!"
txt_s3tup_msg_library_not_found="${txt_lib} not found in config file!"
txt_s3tup_msg_cross_toolchain_log="creating cross ${txt_tc} log"
txt_s3tup_msg_cross_toolchain_commandlist="command list for cross ${txt_tc} creation"
txt_s3tup_msg_cross_toolchain_library_detection="The following libraries were detected in the existing ${txt_tc}:"
txt_s3tup_msg_cross_toolchain_library_integration="The following libraries will now be integrated into the ${txt_tc}:"
txt_s3tup_msg_cross_migrations_renamed="was renamed to"
txt_s3tup_msg_cross_migrations_remove="Remove ${txt_tc}"
txt_s3tup_msg_cross_migrations_outdated="The following cross ${txt_tc}s are out of date due to the renaming of cross ${txt_tc} ${txt_tpl}s:"
txt_s3tup_msg_cross_migrations_outdated2="The following ${txt_tc,,} ${txt_conf}s are out of date due to the correction of some parameters and are corrected automatically:"
txt_s3tup_msg_cross_migrations_hint="You can still use the ${y_l}old cross ${txt_tc}s${re_} from above, but it's better to create new ones based on the ${p_l}new cross ${txt_tc} ${txt_tpl}s${re_} to get future ${txt_tpl} updates.\nThe ${y_l}old cross ${txt_tc}s${re_} can be removed manually as follows:"
txt_s3tup_msg_build_library_log="updating ${txt_lib} log"
txt_s3tup_msg_build_library_commandlist="build command list for"
txt_s3tup_msg_build_library_error="ERRORS on build found, details:"
txt_s3tup_msg_ctng_setup_log="installing crosstool-NG log"
txt_s3tup_msg_ctng_setup_commandlist="build command list for"
txt_s3tup_msg_ctng_setup_cleanup="Cleanup source directory"
txt_s3tup_msg_fng_setup_log="installing freetz-ng log"
txt_s3tup_msg_fng_setup_commandlist="build command list for"
txt_s3tup_msg_fng_setup_cleanup="Cleanup source directory"
txt_s3tup_msg_extract_file_unreadable="file is unreadable:"
txt_s3tup_msg_extract_extension_unknown="unrecognized file extension:"
txt_s3tup_msg_gtp_missing="missing description"
txt_s3tup_msg_gtp_info="run \Zr<${txt_s3tup_menu_command_label_setup}>\ZR to show details"
txt_s3tup_msg_paktc="Press any key to continue"
txt_s3tup_msg_check_toolchain_empty="Parameter${w_l} ${txt_tc} not set!"
txt_s3tup_msg_check_toolchain_not_supported="${txt_tc} ${txt_lib} update not supported!"
txt_s3tup_msg_check_library_info1="Check for PCSC header files and try to symlink to the correct PCSC header files if the last compiler include path points to the wrong location..."
txt_s3tup_msg_check_library_info2a="Symlink to the correct PCSC header files created."
txt_s3tup_msg_check_library_info2b="No PCSC header files found in following folder and it's sub directories:"
txt_s3tup_msg_check_library_info3a="PCSC header files are in the correct location:"
txt_s3tup_msg_check_library_info3b="Compiler returns no include directories!"
txt_s3tup_msg_github_api_limits_info1="Your ${r_l}Github API rate limit has been exceeded${y_l} and will be reset at the following time:"
txt_s3tup_msg_github_api_limits_info2="Please wait until you reset your configuration file. The most recent versions and download links for the libraries are determined dynamically via the Github API. Exceeding the rate limit of the Github API will result in failures on generationg the configuration file. For ${b_l}unauthenticated requests${y_l}, the rate limit allows ${b_l}up to 60 requests per hour${y_l}. Unauthenticated requests are associated with the originating IP address, and not the user making requests."
txt_s3tup_msg_check_crosstool_setup_info="is not setup correctly. Try to fix it automatically..."
txt_s3tup_msg_check_config_info1="Your config file seems to be outdated. The following settings are missing:"
txt_s3tup_msg_check_config_info2="Please restart s3 as follows to recreate an updated config file:"
txt_s3tup_msg_change_config_error="variable does not exist in the configuration file!"
txt_s3tup_msg_change_config_info="Variable changed to:"
txt_s3tup_msg_create_config_template_not_found="Template file not found. Please make a clean checkout of simplebuild 3!"
txt_s3tup_msg_create_config_jq_not_found="Without the package 'jq' automatic config file generation is not possible. Please install it first:"

txt_s3tup_menu_toolchain_title="${txt_tc} Menu"
txt_s3tup_menu_toolchain_text1="Select one of the"
txt_s3tup_menu_toolchain_text2="installed cross ${txt_tc}s that you want to update:"
txt_s3tup_menu_toolchain_notfound="no ${txt_tc}s found"
txt_s3tup_menu_toolchain_folder="$txt_tc folder:"
txt_s3tup_menu_toolchain_config="config file:"

txt_s3tup_menu_library_title="${txt_lib} Update Menu"
txt_s3tup_menu_library_text1="Select all libraries to update in ${txt_tc}'s SYSROOT folder:"
txt_s3tup_menu_library_text2="         ${txt_lib}   version NEW                   CURRENT" #56 chars
txt_s3tup_menu_library_notfound="no libraries found"
txt_s3tup_menu_library_wrong_selection="Don't integrate the same library with different versions!"

txt_s3tup_menu_template_title="Cross ${txt_tc} ${txt_tpl} Menu"
txt_s3tup_menu_template_text1="Select one of the"
txt_s3tup_menu_template_text2="${txt_tpl}s to create the cross ${txt_tc} you want:"
txt_s3tup_menu_template_text3="NOTE:"
txt_s3tup_menu_template_text4="If you create a cross ${txt_tc} from a ${txt_tpl} with a red colored description, an existing one with the same name will be replaced without asking!"
txt_s3tup_menu_template_text5="Dark red colored descriptions indicates that the version of the ${txt_tpl} is higher than the existing ${txt_tc}. An update could make sense."
txt_s3tup_menu_template_notfound="no ${txt_tpl}s found"

txt_s3tup_menu_info_toolchain="${txt_tc}: " #11 chars
txt_s3tup_menu_info_compiler="Compiler:  "  #11 chars
txt_s3tup_menu_info_sysroot="Sysroot:   "   #11 chars
txt_s3tup_menu_info_prefix="Prefix:    "    #11 chars
txt_s3tup_menu_info_include="Include:   "   #11 chars
txt_s3tup_menu_info_library="Configuration:"
txt_s3tup_menu_info_build="command list:"

txt_s3tup_menu_edit_title="Save Cross ${txt_tc} ${txt_tpl}"
txt_s3tup_menu_edit_text="Would you like to \ZrSAVE\ZR this ${txt_tc} ${txt_tpl} \Zrnow\ZR?"

txt_s3tup_menu_backup_title="$txt_s3tup_menu_command_label_backup"
txt_s3tup_menu_build_library_title="Build"
txt_s3tup_menu_ctng_setup_title="$txt_s3tup_menu_command_label_setup"
txt_s3tup_menu_fng_setup_title="$txt_s3tup_menu_command_label_setup"
txt_s3tup_menu_download_title="Downloading"
txt_s3tup_menu_compress_title="Compress cross ${txt_tc}"
