#!/bin/bash

#deutsch
txt_as='als'
txt_of='von'
txt_for='für'
txt_b2="baue"
txt_to="nach"
txt_now='nun'
txt_new='neuer'
txt_b1='bauen'
txt_menu='Menü'
txt_no='keinen'
txt_name='Name'
txt_use='benutze'
txt_back='zurück'
txt_done=' fertig'
txt_error='Fehler'
txt_missing='fehlt'
txt_sel='auswählen'
txt_delete='lösche'
txt_found='gefunden'
txt_create='erstelle'
txt_load='lade'
txt_loaded='geladen'
txt_loading='    lade' #8 zeichen
txt_profile='Profil'
txt_profiles='Profile'
txt_conf='Konfiguration'
txt_parameter='Parameter'
txt_extracting='  entpacke' #10 zeichen
txt_checking='überprüfe'
txt_wait='bitte warten...'
txt_existing='vorhandenen'
txt_ssh_profiles="SSH $txt_profiles"
txt_not_found='nicht gefunden'
txt_n_installed='ist nicht installiert'
txt_start_menu='Hauptmenü'
txt_back_main="$txt_back zum $txt_start_menu"
txt_too_old='(zu alt wird nicht unterstützt)'
txt_selected='ausgewählten'
txt_update='aktualisiere'
txt_example_name='Beispiel: dm820.stube'
txt_save='speichern'
txt_filename='Dateiname'
txt_LOAD="UPLOAD"
txt_tc="Toolchain"
txt_tpl="Vorlage"
txt_lib="Bibliothek"
txt_repo="Repository"
txt_branch="Branch"
txt_proto="Protokoll"

# menu txt
txt_remove_menu="$txt_tc entfernen"
txt_add_menu="$txt_tc hinzufügen"
txt_main_revision="\n Die aktuelle SVN REVISION ist : r"
txt_bmenu_title="Baumenü"

# help txt
txt_help1="beginnen mit"
txt_help2="Kommandozeilen Parameter sind"
txt_help3="Taste [ENTER] zum fortsetzen..."

# firstmenu ################################################
txt_firstmenu_continue="weiter mit lokalem SVN"
   txt_firstmenu_chose="anderen SVN Stand (7000+) laden"
   txt_firstmenu_cedit="$txt_conf""s Editor starten"
   txt_firstmenu_tcupdate="Toolchain Updater starten"
    txt_firstmenu_lang="Systemsprache manuell $txt_sel"
    txt_firstmenu_exit="simplebuild sofort beenden"

# _toolchain_config_menu ###################################
     txt_config_menu="$txt_conf $txt_menu"
      txt_back_build="$txt_back zum $txt_bmenu_title"
txt_module_configure="oscam Module $txt_sel"
     txt_oscam_extra="oscam Extras USB/PCSC $txt_sel"
     txt_build_extra="build Extras compress/patch $txt_sel"
      txt_build_load="letzte $txt_conf laden"
      txt_build_save="$txt_conf speichern"
     txt_build_reset="$txt_conf $txt_back setzen"
       txt_use_targz='erstelle tar Archiv nach dem Bauen'
       txt_use_patch='patche oscam vor dem Bauen'
    txt_use_compress='Binärkompression von oscam'

# _toolchain_build_menu ####################################
   txt_bmenu_user="Benutzername   "
   txt_bmenu_comp="Compiler       "
   txt_bmenu_debu="Debug Info     "
    txt_bmenu_use="USE_Variablen "
  txt_bmenu_build="oscam jetzt $txt_b1"
 txt_bmenu_config="oscam/Build $txt_conf"
 txt_bmenu_update="${txt_lib}en aktualisieren"
 txt_bmenu_backup="Toolchain sichern"
txt_bmenu_profile="vorhandenes $txt_profile laden"
txt_bmenus_profile="$txt_profile $txt_save"
    txt_bmenu_log="zeige lastbuild.log"
   txt_bmenu_back="$txt_back zur Toolchainauswahl"
    txt_compress1="Dateigröße davor          "
    txt_compress2="Dateigröße danach         "
    txt_compress3="Dateigröße verkleinert auf"

# _toolchain_main_menu ####################################
txt_menu_builder1="Beende simplebuild"
txt_menu_builder2="einen neuen $txt_tc hinzufügen"
txt_menu_builder3="entferne einen installierten $txt_tc"
txt_menu_builder4="Nativ $txt_for"
txt_menu_builder5="einen neuen $txt_tc erstellen"
txt_menu_back="Zurück zum $txt_tc $txt_menu"

# _dialog_checkout ########################################
txt_verify_syscheck='überprüfe System            :'
     txt_verify_svn='überprüfe existierenden SVN :'
     txt_update_svn="$txt_update SVN            :"
    txt_prepare_svn="bereite SVN checkout vor :"
         txt_latest="letzter Stand"

# _load_profile ###########################################
  txt_select_profile_title="Verfügbare $txt_profiles"
        txt_select_profile="bitte ein $txt_profile auswählen"
txt_confirm_profile_select="bitte bestätigen sie die Auswahl von:"
      txt_no_profile_found="kein $txt_profile gefunden in\n\n$profdir"

# _upload_cam #############################################
txt_upload_cam1="ssh $txt_profile existiert nicht"
txt_upload_cam2="ssh $txt_profile gefunden"

# _plugin_update_toolchain #############################################
txt_s3tup_menu_command_label_exit="Beenden"
txt_s3tup_menu_command_label_back="Zurück"
txt_s3tup_menu_command_label_create="Erstellen"
txt_s3tup_menu_command_label_update="Aktualisieren"
txt_s3tup_menu_command_label_backup="Sichern"
txt_s3tup_menu_command_label_start="Start"
txt_s3tup_menu_command_label_info="Info"
txt_s3tup_menu_command_label_setup="Setup"
txt_s3tup_menu_command_label_edit="Bearbeiten"
txt_s3tup_menu_command_label_yes="Ja"
txt_s3tup_menu_command_label_no="Nein"

txt_s3tup_msg_update_hint="wird aktualisiert..."
txt_s3tup_msg_update_restart="Starte neu"
txt_s3tup_msg_update_current="ist aktuell"
txt_s3tup_msg_update_s3update_required="Bitte aktualisieren Sie zuerst Ihre simplebuild3-Installation!"
txt_s3tup_msg_update_directory_unversioned="Update nicht möglich, da das Installationsverzeichnis nicht SVN- oder GIT-versioniert ist!"
txt_s3tup_msg_update_pending="Update ausstehend"
txt_s3tup_msg_update_not_required="kein Update erforderlich"
txt_s3tup_msg_update_finished="Update abgeschlossen auf Version:"
txt_s3tup_msg_update_log="Aktualisierung Plugin Log"
txt_s3tup_msg_syscheck1="Bitte warten während die Abhängigkeiten überprüft werden..."
txt_s3tup_msg_syscheck2="Um dieses Plugin ordnungsgemäß verwenden zu können, müssen folgende Pakete manuell installiert werden:"
txt_s3tup_msg_syscheck3="Das dialog-Programm scheint veraltet zu sein. Für dieses Plugin ist dialog-Version >=1.3 erforderlich, um Menüs korrekt anzuzeigen. Wenn deine Linux Distribution keine aktuelle Version von dialog enthält, dann bitte wie folgt manuell kompilieren und aktualisieren:\n"
txt_s3tup_msg_reset_config1="Verschiebe vorhandene Konfigurationsdatei..."
txt_s3tup_msg_reset_config2="Konfigurationsdatei-Backup="
txt_s3tup_msg_reset_config3="Konfigurationsdatei wird erstellt. Bitte warten..."
txt_s3tup_msg_reset_config4="Konfigurationsdatei="
txt_s3tup_msg_reset_config5="Die Datei kann an die eigenen Bedürfnisse angepasst und erweitert werden."
txt_s3tup_msg_buildasroot_error1="Der Cross ${txt_tc} Erstellungsprozess wurde abgebrochen, da er nicht als Root ausgeführt werden darf!"
txt_s3tup_msg_buildasroot_error2="Wenn Sie sich der Gefahren bewusst sind, die beim Erstellen von ${txt_tc}s als Root auftreten können\n         und wissen was Sie tun, dann können Sie dies mit dem folgenden Befehl erzwingen:"
txt_s3tup_msg_toolchain_exists="${txt_tc} bereits vorhanden!"
txt_s3tup_msg_library_not_found="${txt_lib} in der Konfigurationsdatei nicht gefunden!"
txt_s3tup_msg_cross_toolchain_log="Erstellen des Cross ${txt_tc} Log"
txt_s3tup_msg_cross_toolchain_commandlist="Befehlszeilen für die Cross ${txt_tc} Erstellung"
txt_s3tup_msg_cross_toolchain_library_detection="Die folgenden ${txt_lib}en wurden in der vorhandenen ${txt_tc} erkannt:"
txt_s3tup_msg_cross_toolchain_library_integration="Die folgenden ${txt_lib}en werden nun in die ${txt_tc} integriert:"
txt_s3tup_msg_cross_migrations_renamed="wurde umbenannt in"
txt_s3tup_msg_cross_migrations_remove="Lösche ${txt_tc}"
txt_s3tup_msg_cross_migrations_outdated="Die folgenden Cross ${txt_tc}s sind aufgrund der Umbenennung von Cross ${txt_tc} ${txt_tpl}n veraltet:"
txt_s3tup_msg_cross_migrations_outdated2="Die folgenden ${txt_tc} ${txt_conf}en sind aufgrund der Korrektur einiger Parameter veraltet und werden automatisch korrigiert:"
txt_s3tup_msg_cross_migrations_hint="Die ${y_l}alten Cross ${txt_tc}s${re_} von oben können weiterhin verwendet verwenden. Es ist jedoch besser, aktuelle Cross ${txt_tc}s basierend auf den ${p_l}neuen Cross ${txt_tc} ${txt_tpl}n${re_} zu erstellen, um zukünftige Aktualisierungen nachverfolgen zu können.\nDie ${y_l}alten Cross ${txt_tc}s${re_} können wie folgt manuell entfernt werden:"
txt_s3tup_msg_build_library_log="Aktualisierung ${txt_lib} Log"
txt_s3tup_msg_build_library_commandlist="Befehlszeilen zum Erstellen von"
txt_s3tup_msg_build_library_error="Folgende FEHLER sind beim Erstellen aufgetreten:"
txt_s3tup_msg_ctng_setup_log="Installation crosstool-NG Log"
txt_s3tup_msg_ctng_setup_commandlist="Befehlszeilen zur Installation von"
txt_s3tup_msg_ctng_setup_cleanup="Bereinigung des Verzeichnisses"
txt_s3tup_msg_fng_setup_log="Installation freetz-NG Log"
txt_s3tup_msg_fng_setup_commandlist="Befehlszeilen zur Installation von"
txt_s3tup_msg_fng_setup_cleanup="Bereinigung des Verzeichnisses"
txt_s3tup_msg_andk_setup_log="Installation Android NDK Log"
txt_s3tup_msg_andk_setup_commandlist="${txt_s3tup_msg_ctng_setup_commandlist}"
txt_s3tup_msg_andk_setup_cleanup="${txt_s3tup_msg_ctng_setup_cleanup}"
txt_s3tup_msg_extract_file_unreadable="Datei ist nicht lesbar:"
txt_s3tup_msg_extract_extension_unknown="Unbekannte Dateierweiterung:"
txt_s3tup_msg_gtp_missing="Beschreibung fehlt"
txt_s3tup_msg_gtp_info="\Zr<${txt_s3tup_menu_command_label_setup}>\ZR ausführen, um Details anzuzeigen"
txt_s3tup_msg_paktc="Drücken Sie eine beliebige Taste, um fortzufahren"
txt_s3tup_msg_check_toolchain_empty="Parameter${w_l} ${txt_tc} nicht gesetzt!"
txt_s3tup_msg_check_toolchain_not_supported="${txt_tc} ${txt_lib} Aktualisierung nicht unterstützt!"
txt_s3tup_msg_check_library_info1="Überprüfen der PCSC-Header-Dateien und Erstellen einer Verknüpfung zu den korrekten Header-Dateien, wenn der letzte Compiler Pfad auf den falschen Speicherort verweist..."
txt_s3tup_msg_check_library_info2a="Verknüpfung zu den korrekten PCSC-Header-Dateien erstellt."
txt_s3tup_msg_check_library_info2b="Keine PCSC-Header-Dateien im folgenden Ordner und seinen Unterverzeichnissen gefunden:"
txt_s3tup_msg_check_library_info3a="PCSC-Header-Dateien befinden sich am richtigen Speicherort:"
txt_s3tup_msg_check_library_info3b="Der Compiler gibt keine Include-Verzeichnisse zurück!"
txt_s3tup_msg_github_api_limits_info1="Ihr ${r_l}Github-API-Limit wurde überschritten${y_l} und wird zum folgenden Zeitpunkt zurückgesetzt:"
txt_s3tup_msg_github_api_limits_info2="Bitte warten Sie solange, bis Sie Ihre Konfigurationsdatei zurücksetzen. Die neuesten Versionen und Download-Links für die ${txt_lib} werden dynamisch über die Github-API ermittelt. Das Überschreiten des Limits der Github-API führt zu Fehlern beim Erstellen der Konfigurationsdatei. Für ${b_l}nicht authentifizierte Anfragen${y_l} beträgt das Limit ${b_l}bis zu 60 Anfragen pro Stunde${y_l}. Nicht authentifizierte Anfragen werden der ursprünglichen IP-Adresse zugeordnet und nicht dem anfragenden Benutzer."
txt_s3tup_msg_check_crosstool_setup_info="ist nicht richtig installiert. Es wird versucht, es automatisch zu korrigieren..."
txt_s3tup_msg_check_config_info1="Die Konfigurationsdatei scheint veraltet zu sein:"
txt_s3tup_msg_check_config_info2="Bitte starten Sie s3 wie folgt, um eine aktualisierte Konfigurationsdatei zu erstellen:"
txt_s3tup_msg_change_config_error="Variable wurde nicht in der Konfigurationsdatei gefunden!"
txt_s3tup_msg_change_config_info="Variable geändert in:"
txt_s3tup_msg_create_config_template_not_found="${txt_tpl} für die Konfigurationsdatei wurde nicht gefunden. Bitte simplebuild 3 erneut auschecken!"
txt_s3tup_msg_create_config_jq_not_found="Ohne das Paket 'jq' ist eine automatische Erstellung der Konfigurationsdatei nicht möglich. Bitte installieren Sie es manuell:"
txt_s3tup_msg_table_header_libs_col_key="Aktuelle ${txt_lib}-Schlüssel"
txt_s3tup_msg_table_header_libs_col_update="Aktualisierbar"
txt_s3tup_msg_table_header_libs_col_downgrade="Herabstufbar"
txt_s3tup_msg_table_header_libsversion_col_key="${txt_lib}-Schlüssel"
txt_s3tup_msg_table_header_libsversion_col_curversion="Aktuelle Version"
txt_s3tup_msg_table_header_libsversion_col_newversion="Neue Version"
txt_s3tup_msg_table_header_libsversion_col_update="${txt_s3tup_msg_table_header_libs_col_update}"
txt_s3tup_msg_table_header_libsversion_col_downgrade="${txt_s3tup_msg_table_header_libs_col_downgrade}"

txt_s3tup_menu_toolchain_title="${txt_tc} Menü"
txt_s3tup_menu_toolchain_text1="Wählen Sie eine der"
txt_s3tup_menu_toolchain_text2="installierten Cross-${txt_tc}s aus, die Sie aktualisieren möchten:"
txt_s3tup_menu_toolchain_notfound="Keine ${txt_tc}s gefunden"
txt_s3tup_menu_toolchain_folder="${txt_tc} Verzeichnis:"
txt_s3tup_menu_toolchain_config="Konfigurationsdatei:"

txt_s3tup_menu_library_title="${txt_lib} Aktualisierung Menü"
txt_s3tup_menu_library_text1="Wählen Sie alle zu aktualisierenden ${txt_lib}en im SYSROOT-Verzeichnis der ${txt_tc} aus:"
txt_s3tup_menu_library_text2="         ${txt_lib} Version NEU                   AKTUELL" #56 chars
txt_s3tup_menu_library_notsupported="${txt_lib} wird von diesem ${txt_tc} aufgrund fehlender Compiler-Funktionen nicht unterstützt!"
txt_s3tup_menu_library_notfound="Keine ${txt_lib}en gefunden"
txt_s3tup_menu_library_wrong_selection="Integrieren Sie nicht dieselbe Bibliothek mit verschiedenen Versionen!"

txt_s3tup_menu_template_title="Cross ${txt_tc} ${txt_tpl}n Menü"
txt_s3tup_menu_template_text1="Wählen Sie eine der"
txt_s3tup_menu_template_text2="${txt_tpl}n zum Erstellen der gewünschten Cross ${txt_tc}:"
txt_s3tup_menu_template_text3="HINWEIS:"
txt_s3tup_menu_template_text4="Wenn Sie eine Cross ${txt_tc} aus einer ${txt_tpl} mit einer roten Beschreibung erstellen, wird eine vorhandene ${txt_tc} mit demselben Namen ohne Aufforderung überschrieben!"
txt_s3tup_menu_template_text5="Dunkelrote Beschreibungen zeigen an, dass die Version der ${txt_tpl} höher als die vorhandene ${txt_tc} ist. Ein Update könnte sinnvoll sein."

txt_s3tup_menu_template_notfound="Keine ${txt_tpl}n gefunden"

txt_s3tup_menu_info_toolchain="${txt_tc}: " #11 Zeichen
txt_s3tup_menu_info_compiler="Compiler:  "  #11 Zeichen
txt_s3tup_menu_info_sysroot="Sysroot:   "   #11 Zeichen
txt_s3tup_menu_info_prefix="Prefix:    "    #11 Zeichen
txt_s3tup_menu_info_include="Include:   "   #11 Zeichen
txt_s3tup_menu_info_library="Konfiguration:"
txt_s3tup_menu_info_build="Befehlszeilen:"

txt_s3tup_menu_edit_title="Speichere Cross ${txt_tc} ${txt_tpl}"
txt_s3tup_menu_edit_text="Wollen Sie diese ${txt_tc}-${txt_tpl} \Zrjetzt SPEICHERN\ZR?"

txt_s3tup_menu_backup_title="$txt_s3tup_menu_command_label_backup von"
txt_s3tup_menu_build_library_title="Erstelle"
txt_s3tup_menu_ctng_setup_title="$txt_s3tup_menu_command_label_setup"
txt_s3tup_menu_fng_setup_title="$txt_s3tup_menu_command_label_setup"
txt_s3tup_menu_andk_setup_title="$txt_s3tup_menu_command_label_setup"
txt_s3tup_menu_download_title="Herunterladen von"
txt_s3tup_menu_compress_title="Komprimiere Cross ${txt_tc}"
