#!/bin/bash

#english

txt_as='as'
txt_of='of'
txt_for='for'
txt_b2="build"
txt_to="to"
txt_now='now'
txt_new='new'
txt_b1='build'
txt_menu='menu'
txt_done=' done'
txt_no='no'
txt_use='use'
txt_save='save'
txt_back='back'
txt_error='error'
txt_load='load'
txt_loaded='loaded'
txt_loading='    load' #8 chars
txt_sel='select'
txt_delete='delete'
txt_found='found'
txt_create='create'
txt_conf='configuration'
txt_extracting='extracting' #10 chars
txt_checking='checking'
txt_wait='please wait...'
txt_existing='exists'
txt_profiles='profiles'
txt_not_found='not found'
txt_n_installed='is not installed'
txt_no_download='is not available via download'
txt_back_main="back to main menu"
txt_too_old='(too old or not supported)'
txt_selected='selected'
txt_update='now updating'
txt_tc="Toolchain"
txt_tpl="Template"
txt_lib="Library"
txt_repo="Repository"
txt_branch="Branch"
txt_proto="Protocol"
txt_ssh_profiles="SSH $txt_profiles"
txt_wc="working copy"
txt_wc_deviation="$txt_wc url deviation"

# menu txt
txt_start_menu='Main menu'
txt_remove_menu='Remove toolchain'
txt_add_menu='Add toolchain'
txt_main_revision="\n the local ${REPO^^} revision is : r"

# help txt
txt_help1="begin with"
txt_help2="commandline Parameters are"
txt_help3="[ENTER] to continue..."

# firstmenu ################################################
txt_firstmenu_continue="continue with local ${REPO^^}"
   txt_firstmenu_chose="load a different ${REPO^^} Revision"
   txt_firstmenu_cedit="start configuration editor"
   txt_firstmenu_tcupdate="start toolchain updater"
    txt_firstmenu_lang="manual system language selection"
    txt_firstmenu_exit="close simplebuild now"

# _toolchain_config_menu ###################################
     txt_config_menu="configuration menu"
      txt_back_build="back to build menu"
txt_module_configure="select oscam modules "
     txt_oscam_extra="select oscam libraries/features"
     txt_build_extra="select build extras patch/static"
     txt_stapi="select STAPI variant"
      txt_build_load="load last configuration"
      txt_build_save="save configuration"
     txt_build_reset="reset configuration"

# _toolchain_build_menu#####################################
   txt_bmenu_title="build menu"
    txt_bmenu_user="username       "
    txt_bmenu_comp="compiler       "
    txt_bmenu_debu="debug info     "
     txt_bmenu_use="USE_variables "
   txt_bmenu_build="build oscam now"
  txt_bmenu_config="oscam/build configuration"
  txt_bmenu_update="install/update libraries"
  txt_bmenu_backup="backup toolchain"
 txt_bmenu_profile="load existing $txt_profiles"
txt_bmenus_profile="$txt_profiles $txt_save"
     txt_bmenu_log="show lastbuild.log"
    txt_bmenu_back="back to toolchain selection"
     txt_compress1="filesize before     "
     txt_compress2="filesize after      "
     txt_compress3="filesize reduced to "

# _toolchain_main_menu#####################################
txt_menu_builder1="close simplebuild"
txt_menu_builder2="add new toolchain"
txt_menu_builder3="remove installed toolchain"
txt_menu_builder4="build native for"
txt_menu_builder5="create new toolchain"
txt_menu_back="back to toolchain menu"

# _dialog_checkout
txt_verify_syscheck='check system                :'
	 txt_verify_svn="check existing ${REPO^^}          :"
     txt_update_svn="$txt_update ${REPO^^}            :"
    txt_prepare_svn="prepare ${REPO^^} checkout     :"
         txt_latest="latest ${REPO^^}"

# _load_profile ###########################################
  txt_select_profile_title="available profiles"
        txt_select_profile="please select a profile"
txt_confirm_profile_select="please confirm the selection of:"
      txt_no_profile_found="no profile found in\n\n$profdir"

# _upload_cam #############################################
txt_upload_cam1="ssh profile doesn't exist"
txt_upload_cam2="ssh profile found"

# _plugin_update_toolchain #############################################
txt_s3tup_menu_command_label_exit="Exit"
txt_s3tup_menu_command_label_back="Back"
txt_s3tup_menu_command_label_create="Add"
txt_s3tup_menu_command_label_update="Update"
txt_s3tup_menu_command_label_backup="Backup"
txt_s3tup_menu_command_label_start="Build"
txt_s3tup_menu_command_label_download="Download"
txt_s3tup_menu_command_label_repair="Repair"
txt_s3tup_menu_command_label_info="Info"
txt_s3tup_menu_command_label_setup="Setup"
txt_s3tup_menu_command_label_edit="Edit"
txt_s3tup_menu_command_label_yes="Yes"
txt_s3tup_menu_command_label_no="No"

txt_s3tup_msg_update_hint="is being updated..."
txt_s3tup_msg_update_restart="Restarting"
txt_s3tup_msg_update_current="is up to date"
txt_s3tup_msg_update_s3update_required="Please update your simplebuild3 installation first!"
txt_s3tup_msg_update_directory_unversioned="Update not possible because the installation directory is not ${REPO^^} or ${REPO^^} versioned!"
txt_s3tup_msg_update_pending="update pending"
txt_s3tup_msg_update_not_required="no update required"
txt_s3tup_msg_update_finished="Update completed to version:"
txt_s3tup_msg_update_log="updating plugin log"
txt_s3tup_msg_syscheck1="Please wait while performing checks of required tools and dependencies..."
txt_s3tup_msg_syscheck2="You need to manually install the following packages to use this plugin properly:"
txt_s3tup_msg_syscheck3="Your dialog binary seems to be outdated, this plugin requires dialog >= 1.3 to display menus correctly. If your distribution does not provide a recent version, please compile and update it manually as follows:\n"
txt_s3tup_msg_reset_config1="Moving existing config file..."
txt_s3tup_msg_reset_config2="config file backup="
txt_s3tup_msg_reset_config3="Creating new config file. Please wait..."
txt_s3tup_msg_reset_config4="config file="
txt_s3tup_msg_reset_config5="You can change/extend them to fit your needs."
txt_s3tup_msg_buildasroot_error1="The cross ${txt_tc,,} build process was aborted because it must not run as root!"
txt_s3tup_msg_buildasroot_error2="If you are aware of the danger of building ${txt_tc,,}s as root and you know what you are doing,\n         you can force it with the following command:"
txt_s3tup_msg_toolchain_exists="${txt_tc} already exists!"
txt_s3tup_msg_library_not_found="${txt_lib} not found in config file!"
txt_s3tup_msg_cross_toolchain_log="creating cross ${txt_tc,,} log"
txt_s3tup_msg_cross_toolchain_commandlist="command list for cross ${txt_tc,,} creation"
txt_s3tup_msg_cross_toolchain_library_detection="The following libraries were detected in the existing ${txt_tc,,}:"
txt_s3tup_msg_cross_toolchain_library_integration="The following libraries will now be integrated into the ${txt_tc,,}:"
txt_s3tup_msg_cross_migrations_renamed="was renamed to"
txt_s3tup_msg_cross_migrations_remove="Remove ${txt_tc}"
txt_s3tup_msg_cross_migrations_outdated="The following cross ${txt_tc,,}s are out of date due to the renaming of cross ${txt_tc,,} ${txt_tpl,,}s:"
txt_s3tup_msg_cross_migrations_outdated2="The following ${txt_tc,,} ${txt_conf}s are out of date due to the correction of some parameters and are corrected automatically:"
txt_s3tup_msg_cross_migrations_hint="You can still use the ${y_l}old cross ${txt_tc,,}s${re_} from above, but it's better to create new ones based on the ${p_l}new cross ${txt_tc,,} ${txt_tpl,,}s${re_} to get future ${txt_tpl,,} updates.\nThe ${y_l}old cross ${txt_tc,,}s${re_} can be removed manually as follows:"
txt_s3tup_msg_build_library_log="updating ${txt_lib,,} log"
txt_s3tup_msg_build_library_commandlist="build command list for"
txt_s3tup_msg_build_library_error="ERRORS on build found, details:"
txt_s3tup_msg_ctng_setup_log="installing crosstool-NG log"
txt_s3tup_msg_ctng_setup_commandlist="build command list for"
txt_s3tup_msg_ctng_setup_cleanup="Cleanup source directory"
txt_s3tup_msg_fng_setup_log="installing freetz-NG log"
txt_s3tup_msg_fng_setup_commandlist="${txt_s3tup_msg_ctng_setup_commandlist}"
txt_s3tup_msg_fng_setup_cleanup="${txt_s3tup_msg_ctng_setup_cleanup}"
txt_s3tup_msg_andk_setup_log="installing Android NDK log"
txt_s3tup_msg_andk_setup_commandlist="${txt_s3tup_msg_ctng_setup_commandlist}"
txt_s3tup_msg_andk_setup_cleanup="${txt_s3tup_msg_ctng_setup_cleanup}"
txt_s3tup_msg_extract_file_unreadable="file is unreadable:"
txt_s3tup_msg_extract_extension_unknown="unrecognized file extension:"
txt_s3tup_msg_gtp_missing="missing description"
txt_s3tup_msg_gtp_info="run \Zr<${txt_s3tup_menu_command_label_setup}>\ZR to show details"
txt_s3tup_msg_paktc="Press any key to continue"
txt_s3tup_msg_check_toolchain_empty="Parameter${w_l} ${txt_tc} not set!"
txt_s3tup_msg_check_toolchain_not_supported="${txt_tc} ${txt_lib,,} update not supported!"
txt_s3tup_msg_check_library_info1="Check for PCSC header files and try to symlink to the correct PCSC header files if the last compiler include path points to the wrong location..."
txt_s3tup_msg_check_library_info2a="Symlink to the correct PCSC header files created."
txt_s3tup_msg_check_library_info2b="No PCSC header files found in following folder and it's sub directories:"
txt_s3tup_msg_check_library_info3a="PCSC header files are in the correct location:"
txt_s3tup_msg_check_library_info3b="Compiler returns no include directories!"
txt_s3tup_msg_github_api_limits_info1="Your ${r_l}Github API rate limit has been exceeded${y_l} and will be reset at the following time:"
txt_s3tup_msg_github_api_limits_info2="Please wait until you reset your configuration file. The most recent versions and download links for the libraries are determined dynamically via the Github API. Exceeding the rate limit of the Github API will result in failures on generationg the configuration file. For ${b_l}unauthenticated requests${y_l}, the rate limit allows ${b_l}up to 60 requests per hour${y_l}. Unauthenticated requests are associated with the originating IP address, and not the user making requests."
txt_s3tup_msg_check_crosstool_setup_info="is not setup correctly. Try to fix it automatically..."
txt_s3tup_msg_check_config_info1="Your config file seems to be outdated:"
txt_s3tup_msg_check_config_info2="Please restart s3 as follows to recreate an updated config file:"
txt_s3tup_msg_change_config_error="variable does not exist in the configuration file!"
txt_s3tup_msg_change_config_info="Variable changed to:"
txt_s3tup_msg_create_config_template_not_found="Template file not found. Please make a clean checkout of simplebuild 3!"
txt_s3tup_msg_create_config_jq_not_found="Without the package 'jq' automatic config file generation is not possible. Please install it first:"
txt_s3tup_msg_table_header_libs_col_key="Current ${txt_lib,,} keys"
txt_s3tup_msg_table_header_libs_col_update="Updatable"
txt_s3tup_msg_table_header_libs_col_downgrade="Downgradable"
txt_s3tup_msg_table_header_libsversion_col_key="${txt_lib} key"
txt_s3tup_msg_table_header_libsversion_col_curversion="Current version"
txt_s3tup_msg_table_header_libsversion_col_newversion="New version"
txt_s3tup_msg_table_header_libsversion_col_update="${txt_s3tup_msg_table_header_libs_col_update}"
txt_s3tup_msg_table_header_libsversion_col_downgrade="${txt_s3tup_msg_table_header_libs_col_downgrade}"

txt_s3tup_menu_toolchain_title="${txt_tc} Menu"
txt_s3tup_menu_toolchain_text1="Select one of the"
txt_s3tup_menu_toolchain_text2="installed cross ${txt_tc,,}s that you want to update:"
txt_s3tup_menu_toolchain_notsupported="${txt_tc} may not be supported by this build system ($(uname -m)) due to architecture mismatch!"
txt_s3tup_menu_toolchain_arch="$txt_tc host arch:"
txt_s3tup_menu_toolchain_notfound="no ${txt_tc,,}s found"
txt_s3tup_menu_toolchain_folder="$txt_tc folder:"
txt_s3tup_menu_toolchain_config="config file:"

txt_s3tup_menu_library_title="${txt_lib} Update Menu"
txt_s3tup_menu_library_text1="Select all libraries to update in ${txt_tc,,}'s SYSROOT folder:"
txt_s3tup_menu_library_text2="         ${txt_lib,,}   version NEW                   CURRENT" #56 chars
txt_s3tup_menu_library_notsupported="${txt_lib} is not supported by this ${txt_tc,,} due to lack of compiler capabilities!"
txt_s3tup_menu_library_notfound="no libraries found"
txt_s3tup_menu_library_wrong_selection="Don't integrate the same library with different versions!"

txt_s3tup_menu_template_title="Cross ${txt_tc} ${txt_tpl} Menu"
txt_s3tup_menu_template_text1="Select one of the"
txt_s3tup_menu_template_text2="${txt_tpl,,}s to create the cross ${txt_tc,,} you want:"
txt_s3tup_menu_template_text3="NOTE:"
txt_s3tup_menu_template_text4="If you download/create a cross ${txt_tc,,} from a ${txt_tpl,,} with a red colored description, an existing one with the same name will be replaced without asking!"
txt_s3tup_menu_template_text5="Dark red colored descriptions indicates that the version of the ${txt_tpl,,} is higher than the existing ${txt_tc,,}. An update could make sense."
txt_s3tup_menu_template_notfound="no ${txt_tpl,,}s found"

txt_s3tup_menu_info_toolchain="${txt_tc}: " #11 chars
txt_s3tup_menu_info_compiler="Compiler:  "  #11 chars
txt_s3tup_menu_info_sysroot="Sysroot:   "   #11 chars
txt_s3tup_menu_info_prefix="Prefix:    "    #11 chars
txt_s3tup_menu_info_include="Include:   "   #11 chars
txt_s3tup_menu_info_library="Configuration:"
txt_s3tup_menu_info_build="command list:"

txt_s3tup_menu_edit_title="Save Cross ${txt_tc} ${txt_tpl}"
txt_s3tup_menu_edit_text="Reloading Cross Toolchain Template Menu..."

txt_s3tup_menu_backup_title="$txt_s3tup_menu_command_label_backup"
txt_s3tup_menu_build_library_title="Build"
txt_s3tup_menu_ctng_setup_title="$txt_s3tup_menu_command_label_setup"
txt_s3tup_menu_fng_setup_title="$txt_s3tup_menu_command_label_setup"
txt_s3tup_menu_andk_setup_title="$txt_s3tup_menu_command_label_setup"
txt_s3tup_menu_download_title="Downloading"
txt_s3tup_menu_compress_title="Compress cross ${txt_tc,,}"
