#!/bin/bash

#spanish
txt_as='como';
txt_of='de';
txt_for='para';
txt_b2="compilar";
txt_to="a";
txt_now='ahora';
txt_b1='compilar';
txt_menu='menu';
txt_done=' listo';
txt_no='no';
txt_use='usa';
txt_back='atras';
txt_error='error';
txt_loading='cargando'; #8 chars
txt_sel='selección';
txt_delete='borrar';
txt_found='encontrado';
txt_create='crear';
txt_conf='configuración';
txt_extracting='extrayendo'; #10 chars
txt_checking='comprobando';
txt_wait='espera...';
txt_existing='existe';
txt_profiles='perfiles';
txt_not_found='no encontrado';
txt_n_installed='no está instalado';
txt_back_main="Volver al menu";
txt_too_old='(demasiado antiguo o no soportado)';
txt_selected='seleccionado';
txt_update='actualizando';
txt_tc="Toolchain";
txt_tpl="Modelo"
txt_lib="Librería"
txt_repo="Depósito"
txt_branch="Branch"
txt_proto="Protocol"

# menu txt
txt_start_menu='menu principal';
txt_remove_menu='Eliminar toolchain';
txt_add_menu='nueva toolchain';
txt_main_revision="\n la revisión ${REPO^^} es : r";

# help txt
txt_help1="empieza por"
txt_help2="Los parametros del commandline son"
txt_help3="[ENTER] para continuar..."

# firstmenu ################################################
txt_firstmenu_continue="Continuar con el ${REPO^^} local";
   txt_firstmenu_chose="Cargar un ${REPO^^} Revision diferente";
   txt_firstmenu_cedit="Lanzar editor de configuración";
    txt_firstmenu_lang="Selección de idioma";
    txt_firstmenu_exit="Cerrar SimpleBuild ahora";

# _toolchain_config_menu ###################################
     txt_config_menu="menu configuración";
      txt_back_build="volver al menu de compilación";
txt_module_configure="seleccionar modulos oscam ";
     txt_oscam_extra="seleccionar extras oscam libraries/features";
     txt_build_extra="seleccionar extras de compilación parchar/static";
     txt_stapi="seleccionar STAPI variant"
      txt_build_load="cargar la última configuración";
      txt_build_save="guardar configuración";
     txt_build_reset="reiniciar configuración";

# _toolchain_build_menu#####################################
 txt_bmenu_title="menu compilación";
  txt_bmenu_user="usuario        ";
  txt_bmenu_comp="compilador     ";
  txt_bmenu_debu="info depuración ";
   txt_bmenu_use="USE_variables ";
 txt_bmenu_build="compilar oscam ahora";
txt_bmenu_config="Configuración oscam/build";
   txt_bmenu_log="consultar lastbuild.log";
  txt_bmenu_back="volver a la selección del toolchain";
   txt_compress1="filesize antes     ";
   txt_compress2="filesize después      ";
   txt_compress3="filesize reducido a ";

# _toolchain_main_menu#####################################
txt_menu_builder1="cerrar simplebuild";
txt_menu_builder2="Cambiar toolchain";
txt_menu_builder3="Eliminar la toolchain instalada";
txt_menu_builder4="Compilar sistema nativo =>";
txt_menu_back="volver al menu de la toolchain";

# _dialog_checkout
txt_verify_syscheck='comprobación del sistema             :';
     txt_verify_svn="comprobación del ${REPO^^} existente       :";
     txt_update_svn="$txt_update ${REPO^^}                      :";
    txt_prepare_svn="preparación ${REPO^^} checkout             :";
         txt_latest="ultimo ${REPO^^}";

# _load_profile ###########################################
  txt_select_profile_title="perfiles disponibles";
        txt_select_profile="selecciona un perfil";
txt_confirm_profile_select="confirma la selección para:";
      txt_no_profile_found="perfil no encontrado en\n\n$profdir";

# _upload_cam #############################################
txt_upload_cam1="perfil ssh no existente";
txt_upload_cam2="perfil ssh encontrado";

# _plugin_update_toolchain #############################################
txt_s3tup_menu_command_label_exit="Salir"
txt_s3tup_menu_command_label_back="Atrás"
txt_s3tup_menu_command_label_create="Generar"
txt_s3tup_menu_command_label_update="Actualizar"
txt_s3tup_menu_command_label_backup="Copiar"
txt_s3tup_menu_command_label_start="Empezar"
txt_s3tup_menu_command_label_info="Info"
txt_s3tup_menu_command_label_setup="Instalar"
txt_s3tup_menu_command_label_edit="Modificar"
txt_s3tup_menu_command_label_yes="Sí"
txt_s3tup_menu_command_label_no="No"

txt_s3tup_msg_update_hint="se está actualizando..."
txt_s3tup_msg_update_restart="Reiniciando"
txt_s3tup_msg_update_current="está al día"
txt_s3tup_msg_update_s3update_required="Por favor, actualiza tu instalación de simplebuild3 primero!"
txt_s3tup_msg_update_directory_unversioned="No puedo actualizar ya que no hay una versión ${REPO^^} o ${REPO^^} para el directorio de instalación!"
txt_s3tup_msg_update_pending="Actualización pendiente"
txt_s3tup_msg_update_not_required="no hace falta actualizar"
txt_s3tup_msg_update_finished="Actualización terminada a la versión:"
txt_s3tup_msg_update_log="Actualizando log plugin"
txt_s3tup_msg_syscheck1="Por favor, espera mientras compruebo las herramientas y dependencias necesarias..."
txt_s3tup_msg_syscheck2="Necesitas instalar manualmente los siguientes paquetes para usar este plugin correctamente:"
txt_s3tup_msg_syscheck3="Your dialog binary seems to be outdated, this plugin requires dialog >= 1.3 to display menus correctly. If your distribution does not provide a recent version, please compile and update it manually as follows:\n"
txt_s3tup_msg_reset_config1="Moviendo el archivo de configuración existente..."
txt_s3tup_msg_reset_config2="copia archivo de config="
txt_s3tup_msg_reset_config3="Creando un nuevo archivo de configuración. Por favor, espera..."
txt_s3tup_msg_reset_config4="archivo de config="
txt_s3tup_msg_reset_config5="Puedes cambiarlos/ampliarlos para que se adapten a tus necesidades."
txt_s3tup_msg_buildasroot_error1="El procedimiento de compilación cross ${txt_tc,,} ha sido anulado porque no se puede ejecutar como root!"
txt_s3tup_msg_buildasroot_error2="Si eres consciente del peligro de compilar ${txt_tc,,}s como root y sabes lo que estás haciendo,\n         puedes forzarlo con el siguiente comando:"
txt_s3tup_msg_toolchain_exists="${txt_tc} ya existe!"
txt_s3tup_msg_library_not_found="${txt_lib} no encontrado en el archivo config!"
txt_s3tup_msg_cross_toolchain_log="generando el log cross de ${txt_tc,,}"
txt_s3tup_msg_cross_toolchain_commandlist="lista de comandos para la creación de la cross ${txt_tc,,}"
txt_s3tup_msg_cross_toolchain_library_detection="Se detectaron las siguientes librerías en la ${txt_tc,,} existente:"
txt_s3tup_msg_cross_toolchain_library_integration="Las siguientes librerías se integrarán ahora en la ${txt_tc,,}:"
txt_s3tup_msg_cross_migrations_renamed="se renombró a"
txt_s3tup_msg_cross_migrations_remove="Eliminar ${txt_tc}"
txt_s3tup_msg_cross_migrations_outdated="Las crosses siguientes ${txt_tc,,}s están obsoletas debido al renombre de la ${txt_tc,,} ${txt_tpl,,}s:"
txt_s3tup_msg_cross_migrations_outdated2="Las siguientes ${txt_tc,,} ${txt_conf}s están obsoletas debido a la modificación de algunos parámetros y se corregirán automáticamente:"
txt_s3tup_msg_cross_migrations_hint="Todavía puedes usar la vieja cross ${y_l} ${txt_tc,,}s${re_} desde arriba, pero es mejor crear nuevas basadas en la nueva cross ${p_l} ${txt_tc,,} ${txt_tpl,,}s${re_} para recibir actualizaciones futuras de ${txt_tpl,,}.\nLa cross obsoleta ${y_l} ${txt_tc,,}s${re_} se puede eliminar manualmente de la siguiente manera:"
txt_s3tup_msg_build_library_log="Actualizando log de ${txt_lib,,}"
txt_s3tup_msg_build_library_commandlist="Generar lista de comandos para"
txt_s3tup_msg_build_library_error="se han encontrado ERRORES en la compilación, detalles:"
txt_s3tup_msg_ctng_setup_log="instalando el log crosstool-NG"
txt_s3tup_msg_ctng_setup_commandlist="Generar lista de comandos para"
txt_s3tup_msg_ctng_setup_cleanup="Limpiar carpeta fuente"
txt_s3tup_msg_fng_setup_log="instalando log freetz-NG"
txt_s3tup_msg_fng_setup_commandlist="${txt_s3tup_msg_ctng_setup_commandlist}"
txt_s3tup_msg_fng_setup_cleanup="${txt_s3tup_msg_ctng_setup_cleanup}"
txt_s3tup_msg_andk_setup_log="instalando log Android NDK"
txt_s3tup_msg_andk_setup_commandlist="${txt_s3tup_msg_ctng_setup_commandlist}"
txt_s3tup_msg_andk_setup_cleanup="${txt_s3tup_msg_ctng_setup_cleanup}"
txt_s3tup_msg_extract_file_unreadable="El archivo es ilegible:"
txt_s3tup_msg_extract_extension_unknown="extensión de archivo no reconocida:"
txt_s3tup_msg_gtp_missing="Descripción inexistente"
txt_s3tup_msg_gtp_info="ejecutar \Zr<${txt_s3tup_menu_command_label_setup}>\ZR para mostrar los detalles"
txt_s3tup_msg_paktc="Presiona cualquier tecla para continuar"
txt_s3tup_msg_check_toolchain_empty="Parametros${w_l} ${txt_tc} no ajustados!"
txt_s3tup_msg_check_toolchain_not_supported="${txt_tc} ${txt_lib,,} actualización no soportada!"
txt_s3tup_msg_check_library_info1="Revisa los archivos de encabezado PCSC e intenta enlazar con los archivos de encabezado PCSC correctos si la última ruta de include del compilador indica una posición incorrecta..."
txt_s3tup_msg_check_library_info2a="Enlace simbólico a los archivos de encabezamiento PCSC correctos creado."
txt_s3tup_msg_check_library_info2b="No se encontraron archivos de encabezamiento PCSC en el siguiente directorio y sus subdirectorios:"
txt_s3tup_msg_check_library_info3a="Los archivos de encabezamiento del PCSC están en la posición correcta:"
txt_s3tup_msg_check_library_info3b="El compilador no devuelve directorios de include!"
txt_s3tup_msg_github_api_limits_info1="Tu limite de ${r_l}Github API ha sido excedido${y_l} y será restablecido en el siguiente momento:"
txt_s3tup_msg_github_api_limits_info2="Por favor, espera hasta que restablezcas tu archivo de configuración. Las versiones más recientes y los enlaces de descarga de las librerías se determinan dinámicamente a través de la API de Github. Si se supera el límite de la API de Github, se producirán fallos en la generación del archivo de configuración. Para las solicitudes no autenticadas ${b_l}${y_l}, el límite permite a ${b_l}hasta 60 solicitudes por hora${y_l}. Las solicitudes no autenticadas se asocian con la dirección IP de origen, y no con el usuario que hace la solicitud."
txt_s3tup_msg_check_crosstool_setup_info="no está configurado correctamente. Intento de arreglarlo automáticamente..."
txt_s3tup_msg_check_config_info1="Tu archivo de config parece estar obsoleto:"
txt_s3tup_msg_check_config_info2="Por favor, reinicia s3 de la siguiente manera para regenerar un archivo de config actualizado:"
txt_s3tup_msg_change_config_error=":la variable no existe en el archivo de configuración!"
txt_s3tup_msg_change_config_info="Variable modificada en:"
txt_s3tup_msg_create_config_template_not_found="No se encontró el archivo de la plantilla. Por favor, haz una revisión completa de simplebuild 3!"
txt_s3tup_msg_create_config_jq_not_found="Sin el paquete 'jq' la generación automática de archivos de configuración no es posible. Por favor, instálalo primero:"
txt_s3tup_msg_table_header_libs_col_key="Current ${txt_lib,,} keys"
txt_s3tup_msg_table_header_libs_col_update="Updatable"
txt_s3tup_msg_table_header_libs_col_downgrade="Downgradable"
txt_s3tup_msg_table_header_libsversion_col_key="${txt_lib} key"
txt_s3tup_msg_table_header_libsversion_col_curversion="Current version"
txt_s3tup_msg_table_header_libsversion_col_newversion="New version"
txt_s3tup_msg_table_header_libsversion_col_update="${txt_s3tup_msg_table_header_libs_col_update}"
txt_s3tup_msg_table_header_libsversion_col_downgrade="${txt_s3tup_msg_table_header_libs_col_downgrade}"

txt_s3tup_menu_toolchain_title="${txt_tc} Menu"
txt_s3tup_menu_toolchain_text1="Escoge una de las"
txt_s3tup_menu_toolchain_text2="crosses instaladas ${txt_tc,,}s que quieres actualizar:"
txt_s3tup_menu_toolchain_notsupported="${txt_tc} may not be supported by this build system ($(uname -m)) due to architecture mismatch!"
txt_s3tup_menu_toolchain_arch="$txt_tc host arch:"
txt_s3tup_menu_toolchain_notfound="no se ha encontrado ${txt_tc,,}s"
txt_s3tup_menu_toolchain_folder="directorio $txt_tc:"
txt_s3tup_menu_toolchain_config="archivo config:"

txt_s3tup_menu_library_title="${txt_lib} Menu Actualización"
txt_s3tup_menu_library_text1="Escoge todas las librerías a actualizar en la carpeta SYSROOT de ${txt_tc,,}:"
txt_s3tup_menu_library_text2="         ${txt_lib,,}   versión NUEVA                   ACTUAL" #56 chars
txt_s3tup_menu_library_notsupported="${txt_lib} is not supported by this ${txt_tc,,} due to lack of compiler capabilities!"
txt_s3tup_menu_library_notfound="no se han encontrado librerías"
txt_s3tup_menu_library_wrong_selection="No integres la misma librería en diferentes versiones!"

txt_s3tup_menu_template_title="Cross ${txt_tc} ${txt_tpl} Menu"
txt_s3tup_menu_template_text1="Escoge una de las"
txt_s3tup_menu_template_text2="${txt_tpl,,}s para generar la cross ${txt_tc,,} deseada:"
txt_s3tup_menu_template_text3="NOTA:"
txt_s3tup_menu_template_text4="Si creas una cross ${txt_tc,,} de un ${txt_tpl,,} con una descripción de color rojo, una existente con el mismo nombre será reemplazada sin preguntar!"
txt_s3tup_menu_template_text5="Las descripciones de color rojo oscuro indican que la versión del ${txt_tpl,,} es más alta que la existente ${txt_tc,,}. Se recomienda una actualización."
txt_s3tup_menu_template_notfound="no ${txt_tpl,,}s encontrado"

txt_s3tup_menu_info_toolchain="${txt_tc}: " #11 chars
txt_s3tup_menu_info_compiler="Compilador:"  #11 chars
txt_s3tup_menu_info_sysroot="Sysroot:   "   #11 chars
txt_s3tup_menu_info_prefix="Prefijo:   "    #11 chars
txt_s3tup_menu_info_include="Include:   "   #11 chars
txt_s3tup_menu_info_library="Configuración:"
txt_s3tup_menu_info_build="lista de comandos:"

txt_s3tup_menu_edit_title="Guardar Cross ${txt_tc} ${txt_tpl}"
txt_s3tup_menu_edit_text="¿Quieres \ZrGUARDAR\ZR esta ${txt_tc,,} ${txt_tpl,,} \Zrahora\ZR?"

txt_s3tup_menu_backup_title="$txt_s3tup_menu_command_label_backup"
txt_s3tup_menu_build_library_title="Compilar"
txt_s3tup_menu_ctng_setup_title="$txt_s3tup_menu_command_label_setup"
txt_s3tup_menu_fng_setup_title="$txt_s3tup_menu_command_label_setup"
txt_s3tup_menu_andk_setup_title="$txt_s3tup_menu_command_label_setup"
txt_s3tup_menu_download_title="Descargando"
txt_s3tup_menu_compress_title="Comprimir cross ${txt_tc,,}"
