#!/bin/bash

#nederlands

txt_as='als';
txt_of='van';
txt_for='voor';
txt_b2="build";
txt_to="naar";
txt_now='nu';
txt_b1='compileren';
txt_menu='Menu';
txt_no='geen';
txt_name='Naam';
txt_use='gebruik';
txt_back='terug';
txt_done=' klaar';
txt_error='Fout';
txt_missing='ontbreekt';
txt_sel='selecteren';
txt_delete='verwijderen';
txt_found='gevonden';
txt_create='maak';
txt_loading='   laden';
txt_profile='profiel';
txt_profiles='Profielen';
txt_conf='Configuratie';
txt_parameter='Parameter';
txt_extracting='uitpakken';
txt_wait='momentje...';
txt_existing='bestaande';
txt_ssh_profiles='SSH $txt_profiles';
txt_not_found='niet gevonden';
txt_n_installed='is niet geïnstalleerd';
txt_start_menu='Hoofdmenu';
txt_back_main="$txt_back naar $txt_start_menu";
txt_too_old='(te oud of niet ondersteund)';
txt_selected='geselecteerd';
txt_update='nu bijwerken';
txt_example_name='Voorbeeld: dm820.slaapkmr';
txt_save='opslaan';
txt_filename='Bestandsnaam';
txt_LOAD="UPLOAD";
txt_tc="Toolchain";

# menu txt
txt_remove_menu='$txt_tc verwijderen';
txt_add_menu='$txt_tc toevoegen';
txt_main_revision="\n De actuele SVN versie is : r";
txt_bmenu_title="Buildmenü";

# help txt
txt_help1="begin met"
txt_help2="Opdrachtregel parameters zijn"
txt_help3="Druk op [ENTER] om door te gaan..."

# firstmenu ################################################
txt_firstmenu_continue="Doorgaan met lokale SVN";
   txt_firstmenu_chose="Andere SVN versie (7000+) laden";
   txt_firstmenu_cedit="$txt_conf""s Editor starten";
    txt_firstmenu_lang="Taal handmatig $txt_sel";
    txt_firstmenu_exit="Afsluiten";

# _toolchain_config_menu ###################################
     txt_config_menu="$txt_conf $txt_menu";
      txt_back_build="$txt_back naar $txt_bmenu_title";
txt_module_configure="Oscam module $txt_sel";
     txt_oscam_extra="Oscam extra's USB/PCSC $txt_sel";
     txt_build_extra="build Extra's Compress/Patch $txt_sel";
      txt_build_load="Laatste $txt_conf laden";
      txt_build_save="$txt_conf bewaren";
     txt_build_reset="$txt_conf $txt_back zetten";
       txt_use_targz='maak .tar bestand na het compileren';
       txt_use_patch='patch oscam voor het compileren';
    txt_use_compress='Binaire compressie van oscam';

# _toolchain_build_menu ####################################
  txt_bmenu_user="Gebruikersnaam ";
  txt_bmenu_comp="Compiler       ";
  txt_bmenu_debu="Debug info     ";
   txt_bmenu_use="GEBRUIK variabelen ";
 txt_bmenu_build="OScam nu $txt_b1";
txt_bmenu_config="OScam/Build $txt_conf";
txt_bmenu_profile="beschikbare $txt_profile laden";
txt_bmenus_profile="$txt_profile $txt_save";
   txt_bmenu_log="Toon lastbuild.log";
  txt_bmenu_back="$txt_back naar $txt_tc selectie";
   txt_compress1="Bestandgrootte eerst         ";
   txt_compress2="Bestandgrootte na            ";
   txt_compress3="Bestandgrootte verkleind tot ";

# _toolchain_main_menu#####################################
txt_menu_builder1="Simplebuild afsluiten";
txt_menu_builder2="Voeg nieuwe $txt_tc toe";
txt_menu_builder3="Verwijder geïnstalleerde $txt_tc";
txt_menu_builder4="Huidig system:";
txt_menu_back="Naar $txt_tc $txt_menu";

# _dialog_checkout
txt_verify_syscheck='Systeem controleren       :';
     txt_verify_svn='Huidige SVN controleren   :';
     txt_update_svn="SVN $txt_update           :";
    txt_prepare_svn="SVN controle voorbereiden :";
         txt_latest="Nieuwste SVN";

# _load_profile ###########################################
  txt_select_profile_title="Beschikbare $txt_profiles";
        txt_select_profile="Kies een $txt_profile a.u.b.";
txt_confirm_profile_select="Bevestig a.u.b. de keuze van:";
      txt_no_profile_found="geen $txt_profile gevonden in\n\n$profdir";

# _upload_cam #############################################
txt_upload_cam1="ssh $txt_profile bestaat niet";
txt_upload_cam2="ssh $txt_profiles gevonden";
